# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
- repo: self

pool:
 name: Default

variables:
 dockerComposePath: '$(Pipeline.Workspace)/s'

stages:
- stage: DockerCompose
  displayName: DockerCompose
  jobs:
  - job: DockerCompose
    displayName: DockerCompose
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cd $(dockerComposePath)
                docker-compose -f docker-compose.yml up -d
