# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
- repo: self

variables:
 dockerComposePath: '$(Pipeline.Workspace)/s'

stages:
- stage: DeployToQA
  displayName: DeployToQA
  jobs:
  - deployment: DeployToQA
    environment: 'QA'
    strategy:      
     runOnce:        
      deploy:
       steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
                            cd $(dockerComposePath)
                            docker compose -f docker-compose2.yml up -d
                            displayName: 'Run Docker Compose'
