# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: 
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'bf47c0e3-8964-48e3-a1ca-c2b86bf001a6'
  imageRepository: 'workerapp'
  containerRegistry: 'hadii.azurecr.io'
  dockerfilePath: '$(Pipeline.Workspace)/s/worker/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: Default

stages:
- stage: Build_WorkerApp
  displayName: Build and push stage
  jobs:
  - job: Build_WorkerApp
    displayName: Build_WorkerApp
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
          $(tag)
