# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
- repo: self

pool:
 name: Default

variables:
 dockerComposePath: '/home/azureuser/azagent/azagent/_work/1/s'

stages:
- stage: DeployToVM
  displayName: 'Deploy to VM Environment'
  jobs:
  - deployment: DeployToVM
    displayName: 'Deploy to VM'
    environment: 
     name: QA
     resourceName: QA-Server
     resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'pwd'

