---
version: '3.8'

services:
 voting-app:
 image: hadii.azurecr.io/votingapp:latest
 ports:
 - 5050:80

 redis-app:
  image: redis
  ports:
  - 6379: 6379

 worker-app:
  image: hadii.azurecr.io/workerapp:latest

 postgres-app:
  image: postgres
  environment:
   POSTGRES_PASSWORD: intelliqit
   POSTGRES_USER: myuser
   POSTGRES_DB: mydb
  ports:
  - 5432:5432

 result-app:
  image: hadii.azurecr.io/resultapp:latest
  ports:
  - 6060:80
